# Generated by Django 3.0.3 on 2020-04-20 05:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('log_sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('teacher', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='judgement_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2020, 4, 20, 13, 7, 48, 85788))),
                ('evaluation', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_search_judgement.course')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_sign.normal_user')),
            ],
        ),
    ]
