# Generated by Django 3.0.3 on 2020-04-27 00:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search_judgement', '0002_auto_20200423_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 27, 8, 44, 24, 613842)),
        ),
    ]
