# Generated by Django 3.0.3 on 2020-04-30 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search_judgement', '0003_auto_20200427_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgement_system',
            name='evaluation',
        ),
        migrations.AddField(
            model_name='judgement_system',
            name='comment_of_the_course',
            field=models.CharField(default='good', max_length=300),
        ),
        migrations.AddField(
            model_name='judgement_system',
            name='comment_of_the_teacher',
            field=models.CharField(default='good', max_length=300),
        ),
        migrations.AddField(
            model_name='judgement_system',
            name='the_constitution_of_grade',
            field=models.CharField(default='good', max_length=50),
        ),
        migrations.AddField(
            model_name='judgement_system',
            name='time_for_homework',
            field=models.CharField(default='good', max_length=100),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 7, 48, 515969)),
        ),
    ]
