# Generated by Django 3.0.3 on 2020-04-30 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search_judgement', '0004_auto_20200430_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement_system',
            name='comment_of_the_course',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='comment_of_the_teacher',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 9, 57, 433251)),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='the_constitution_of_grade',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='time_for_homework',
            field=models.CharField(max_length=100),
        ),
    ]
