# Generated by Django 3.0.3 on 2020-05-03 02:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search_judgement', '0005_auto_20200430_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement_system',
            name='mark',
            field=models.DecimalField(decimal_places=0, default=5, max_digits=1),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 10, 9, 52, 865275)),
        ),
    ]
