# Generated by Django 3.0.3 on 2020-05-03 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search_judgement', '0010_auto_20200503_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 22, 35, 44, 103901)),
        ),
    ]
