# Generated by Django 3.0.3 on 2020-05-05 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_search_judgement', '0012_auto_20200503_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 22, 4, 0, 446446)),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='hard_core_mark',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='mark_of_interest',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='recommend_mark',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
