# Generated by Django 3.0.3 on 2020-05-15 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log_sign', '0001_initial'),
        ('course_search_judgement', '0013_auto_20200505_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgement_system',
            name='number_of_thumb_up',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='judgement_system',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 10, 3, 23, 234156)),
        ),
        migrations.CreateModel(
            name='thumb_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judgement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_search_judgement.judgement_system')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_sign.normal_user')),
            ],
        ),
    ]
